export const bloodGroups = [
    { value: "A+", label: "A+" },
    { value: "A-", label: "A-" },
    { value: "B+", label: "B+" },
    { value: "B-", label: "B-" },
    { value: "AB+", label: "AB+" },
    { value: "AB-", label: "AB-" },
    { value: "O+", label: "O+" },
    { value: "O-", label: "O-" },
    { value: "A1+", label: "A1+" },
    { value: "A1-", label: "A1-" },
    { value: "A2+", label: "A2+" },
    { value: "A2-", label: "A2-" },
    { value: "A1B+", label: "A1B+" },
    { value: "A1B-", label: "A1B-" },
    { value: "A2B+", label: "A2B+" },
    { value: "A2B-", label: "A2B-" },
  ];